### ISSUE TITLE
Modifier les balises <title> et <h1> des pages HTML auto-générées

### ISSUE THREAD

**Issue by kerphi** [transition-bibliographique/ontologie-rda-fr#3]
Demande faite par @AnilAng : 

> Changer dans le html https://rdafr.fr/profil-application/ l'entête de la page en “Profil d’application de l’ontologie RDA-FR” (au lieu de rda-fr)

![image](https://user-images.githubusercontent.com/328244/218972450-3714289b-84be-42e1-932d-b0bd3629f371.png)

> et, idem, un peu plus bas, dans le champ Description, remplacer "Ontologie RDA-FR" par "Profil d’application de l’ontologie RDA-FR pour le code de catalogage RDA-FR" (je pense que c'est ce qui est le plus explicite).

![image](https://user-images.githubusercontent.com/328244/218972523-2581662e-c4a0-4b01-8264-474e2fce9ad6.png)

Ainsi on sera en cohérence avec les changements opérés.

**Comment by kerphi** [comment]
Mes premières recherches sur le sujet : 

A priori c'est prévu de paramétrer cela avec l'outil sparna : https://shacl-play.sparna.fr/play/doc#ontology
et c'est probablement des données à rajouter quelque part dans [profil-application/rdafr.ttl](https://github.com/transition-bibliographique/ontologie-rda-fr/blob/main/profil-application/rdafr.ttl)

cf la doc de sparna : https://shacl-play.sparna.fr/play/doc#ontology
![image](https://user-images.githubusercontent.com/328244/218972649-8a72acc1-1b25-489a-9c06-8ab1a4867bfd.png)

**Comment by eonm-pro** [comment]
Salut @kerphi les tableaux ont été modifiés par @delahousse pour ajouter les métadonnées. Ça a bien fonctionné. C'est en prod.

**Comment by kerphi** [comment]
C'est fait et c'est en prod, je ferme le ticket
