### ISSUE TITLE
Voir comment intégrer le lien Google Docs pour la génération vers les TTL

### ISSUE THREAD

**Issue by kerphi** [transition-bibliographique/ontologie-rda-fr#4]
Par exemple via une github action qui utiliserait l'outil https://skos-play.sparna.fr/play/convert et qui serait déclenchée manuellement au besoin.

cc @eonm-abes

**Comment by kerphi** [comment]
@eonm-abes l'a fait dans cette PR : https://github.com/transition-bibliographique/ontologie-rda-fr/pull/2

**Comment by kerphi** [comment]
@eonm-abes je me demandais si tu pouvais compléter la procédure de mise à jour de rdafr.fr avec cette partie ? 
https://docs.google.com/document/d/1uoeIcUm-9nqG_PXcpNWdT0V6C3CHLqCVSY7SsjRU7vg/edit#heading=h.77e5fvjd4bu6

**Comment by eonm-pro** [comment]
@kerphi je cherchais justement la procédure. Je m'en occupe

**Comment by kerphi** [comment]
Merci @eonm-abes !
